apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-creator
  namespace: regtech
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "list", "get", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-creator-binding
  namespace: regtech
subjects:
- kind: ServiceAccount
  name: cfpb-ci-sa-sqs
  namespace: regtech
roleRef:
  kind: Role
  name: job-creator
  apiGroup: rbac.authorization.k8s.io