fullnameOverride: "sqs-csv-poller"
image:
  repository: 099248080076.dkr.ecr.us-east-1.amazonaws.com/cfpb/regtech/sqs-parquet
  pullPolicy: Always
  tag: "latest"

healthcheck:
  enabled: false

serviceAccount:
  name: cfpb-ci-sa-sqs

envFrom:
- configMapRef:
    name: "{{ .Values.configmap.name }}"

ignore_healthChecks: true

configmap:
  enabled: true
  name: sqs-csv-poller
  data:
    QUEUE_URL: https://sqs.us-east-1.amazonaws.com/099248080076/cfpb-regtech-dev-s3-queue-test
    JOB_IMAGE: "099248080076.dkr.ecr.us-east-1.amazonaws.com/cfpb/regtech/sqs-parquet-job:latest"

volumes:
- name: sqs-csv-poller-secrets
  csi:
    driver: secrets-store.csi.k8s.io
    readOnly: true
    volumeAttributes:
      secretProviderClass: regtech-provider

volumeMounts:
- name: sqs-csv-poller-secrets
  mountPath: "/mnt/secrets-store"
  readOnly: true